[Mon Nov 04 15:18:32.369210 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740] mod_wsgi (pid=2376): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:18:32.369402 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740] mod_wsgi (pid=2376): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:18:32.370561 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740] Traceback (most recent call last):
[Mon Nov 04 15:18:32.370931 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:18:32.370945 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]     from app import app as application
[Mon Nov 04 15:18:32.370969 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:18:32.370977 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]     import commonTasks
[Mon Nov 04 15:18:32.370997 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:18:32.371005 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740]     import gspread
[Mon Nov 04 15:18:32.371046 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:35740] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:18:32.557297 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746] mod_wsgi (pid=2376): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:18:32.557608 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746] mod_wsgi (pid=2376): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:18:32.558440 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746] Traceback (most recent call last):
[Mon Nov 04 15:18:32.559623 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:18:32.559698 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]     from app import app as application
[Mon Nov 04 15:18:32.559738 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:18:32.559746 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]     import commonTasks
[Mon Nov 04 15:18:32.559765 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:18:32.559773 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746]     import gspread
[Mon Nov 04 15:18:32.559835 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:35746] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:23:42.514529 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916] mod_wsgi (pid=2376): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:23:42.514785 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916] mod_wsgi (pid=2376): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:23:42.515806 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916] Traceback (most recent call last):
[Mon Nov 04 15:23:42.517861 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:23:42.518219 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]     from app import app as application
[Mon Nov 04 15:23:42.518369 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:23:42.518406 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]     import commonTasks
[Mon Nov 04 15:23:42.518442 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:23:42.518531 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916]     import gspread
[Mon Nov 04 15:23:42.518665 2024] [wsgi:error] [pid 2376:tid 2412] [remote 127.0.0.1:53916] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:23:42.679242 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920] mod_wsgi (pid=2376): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:23:42.679431 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920] mod_wsgi (pid=2376): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:23:42.679954 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920] Traceback (most recent call last):
[Mon Nov 04 15:23:42.683191 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:23:42.683366 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]     from app import app as application
[Mon Nov 04 15:23:42.683464 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:23:42.683482 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]     import commonTasks
[Mon Nov 04 15:23:42.683511 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:23:42.683519 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920]     import gspread
[Mon Nov 04 15:23:42.683623 2024] [wsgi:error] [pid 2376:tid 2413] [remote 127.0.0.1:53920] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:26:35.888474 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:26:35.888627 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:26:35.889865 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098] Traceback (most recent call last):
[Mon Nov 04 15:26:35.890282 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:26:35.890307 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]     from app import app as application
[Mon Nov 04 15:26:35.890337 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:26:35.890349 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]     import commonTasks
[Mon Nov 04 15:26:35.890373 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:26:35.890384 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098]     import gspread
[Mon Nov 04 15:26:35.890445 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:57098] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:26:36.086418 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:26:36.086737 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:26:36.087273 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114] Traceback (most recent call last):
[Mon Nov 04 15:26:36.087989 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:26:36.088074 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]     from app import app as application
[Mon Nov 04 15:26:36.088130 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:26:36.088188 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]     import commonTasks
[Mon Nov 04 15:26:36.088224 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:26:36.088233 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114]     import gspread
[Mon Nov 04 15:26:36.088309 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:57114] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:29:24.366869 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:24.367184 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:24.373176 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008] Traceback (most recent call last):
[Mon Nov 04 15:29:24.373892 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:29:24.373963 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]     from app import app as application
[Mon Nov 04 15:29:24.373998 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:29:24.374012 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]     import commonTasks
[Mon Nov 04 15:29:24.374036 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:29:24.374048 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008]     import gspread
[Mon Nov 04 15:29:24.374102 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43008] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:29:24.589147 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:24.589320 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:24.589918 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024] Traceback (most recent call last):
[Mon Nov 04 15:29:24.590400 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:29:24.590450 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]     from app import app as application
[Mon Nov 04 15:29:24.590481 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:29:24.590494 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]     import commonTasks
[Mon Nov 04 15:29:24.590518 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:29:24.590530 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024]     import gspread
[Mon Nov 04 15:29:24.590581 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43024] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:29:25.184291 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:25.184758 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:25.185530 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040] Traceback (most recent call last):
[Mon Nov 04 15:29:25.186719 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:29:25.186930 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]     from app import app as application
[Mon Nov 04 15:29:25.187037 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:29:25.187057 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]     import commonTasks
[Mon Nov 04 15:29:25.187084 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:29:25.187093 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040]     import gspread
[Mon Nov 04 15:29:25.187187 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:43040] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:29:25.383928 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:25.384065 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:29:25.384443 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054] Traceback (most recent call last):
[Mon Nov 04 15:29:25.384817 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:29:25.384845 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]     from app import app as application
[Mon Nov 04 15:29:25.384869 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:29:25.384877 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]     import commonTasks
[Mon Nov 04 15:29:25.385612 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:29:25.385676 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054]     import gspread
[Mon Nov 04 15:29:25.385740 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:43054] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:30:54.425922 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:54.426118 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:54.426560 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476] Traceback (most recent call last):
[Mon Nov 04 15:30:54.429709 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:30:54.429938 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]     from app import app as application
[Mon Nov 04 15:30:54.430068 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:30:54.430110 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]     import commonTasks
[Mon Nov 04 15:30:54.430145 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:30:54.430158 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476]     import gspread
[Mon Nov 04 15:30:54.430244 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49476] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:30:54.525533 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:54.525676 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:54.526079 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482] Traceback (most recent call last):
[Mon Nov 04 15:30:54.526442 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:30:54.526469 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]     from app import app as application
[Mon Nov 04 15:30:54.526493 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:30:54.526502 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]     import commonTasks
[Mon Nov 04 15:30:54.526522 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:30:54.526530 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482]     import gspread
[Mon Nov 04 15:30:54.526569 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49482] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:30:58.102114 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:58.102279 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:58.102645 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496] Traceback (most recent call last):
[Mon Nov 04 15:30:58.103019 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:30:58.103043 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]     from app import app as application
[Mon Nov 04 15:30:58.103065 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:30:58.103073 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]     import commonTasks
[Mon Nov 04 15:30:58.103092 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:30:58.103100 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496]     import gspread
[Mon Nov 04 15:30:58.103137 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:49496] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:30:58.180236 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:58.180527 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:30:58.181516 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512] Traceback (most recent call last):
[Mon Nov 04 15:30:58.182468 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:30:58.182548 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]     from app import app as application
[Mon Nov 04 15:30:58.182591 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:30:58.182601 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]     import commonTasks
[Mon Nov 04 15:30:58.182622 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:30:58.182630 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512]     import gspread
[Mon Nov 04 15:30:58.182697 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:49512] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:31:04.421024 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:04.421194 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:04.421582 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244] Traceback (most recent call last):
[Mon Nov 04 15:31:04.421992 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:31:04.422038 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]     from app import app as application
[Mon Nov 04 15:31:04.422069 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:31:04.422082 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]     import commonTasks
[Mon Nov 04 15:31:04.422105 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:31:04.422116 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244]     import gspread
[Mon Nov 04 15:31:04.422158 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41244] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:31:04.537247 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:04.537420 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:04.537814 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252] Traceback (most recent call last):
[Mon Nov 04 15:31:04.538269 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:31:04.538332 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]     from app import app as application
[Mon Nov 04 15:31:04.538371 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:31:04.538384 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]     import commonTasks
[Mon Nov 04 15:31:04.538407 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:31:04.538419 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252]     import gspread
[Mon Nov 04 15:31:04.538466 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41252] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:31:08.003647 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:08.003824 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:08.004219 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266] Traceback (most recent call last):
[Mon Nov 04 15:31:08.004680 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:31:08.004735 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]     from app import app as application
[Mon Nov 04 15:31:08.004794 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:31:08.004808 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]     import commonTasks
[Mon Nov 04 15:31:08.004876 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:31:08.004925 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266]     import gspread
[Mon Nov 04 15:31:08.005003 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:41266] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:31:08.100347 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:08.100494 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:31:08.100924 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280] Traceback (most recent call last):
[Mon Nov 04 15:31:08.101358 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:31:08.101396 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]     from app import app as application
[Mon Nov 04 15:31:08.101424 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:31:08.101433 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]     import commonTasks
[Mon Nov 04 15:31:08.101453 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:31:08.101461 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280]     import gspread
[Mon Nov 04 15:31:08.101515 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:41280] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:33:17.096680 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:33:17.096940 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:33:17.097393 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658] Traceback (most recent call last):
[Mon Nov 04 15:33:17.097892 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:33:17.097949 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]     from app import app as application
[Mon Nov 04 15:33:17.097984 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:33:17.097998 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]     import commonTasks
[Mon Nov 04 15:33:17.098023 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:33:17.098036 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658]     import gspread
[Mon Nov 04 15:33:17.098092 2024] [wsgi:error] [pid 2647:tid 2674] [remote 127.0.0.1:40658] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:33:17.256119 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674] mod_wsgi (pid=2647): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:33:17.256280 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674] mod_wsgi (pid=2647): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:33:17.256642 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674] Traceback (most recent call last):
[Mon Nov 04 15:33:17.257101 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:33:17.257149 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]     from app import app as application
[Mon Nov 04 15:33:17.257220 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:33:17.257229 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]     import commonTasks
[Mon Nov 04 15:33:17.257249 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:33:17.257257 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674]     import gspread
[Mon Nov 04 15:33:17.257296 2024] [wsgi:error] [pid 2647:tid 2685] [remote 127.0.0.1:40674] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:38:17.980606 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518] mod_wsgi (pid=2939): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:38:17.981027 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518] mod_wsgi (pid=2939): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:38:17.983080 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518] Traceback (most recent call last):
[Mon Nov 04 15:38:17.983892 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:38:17.983998 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]     from app import app as application
[Mon Nov 04 15:38:17.984066 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:38:17.984084 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]     import commonTasks
[Mon Nov 04 15:38:17.984114 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:38:17.984129 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518]     import gspread
[Mon Nov 04 15:38:17.984204 2024] [wsgi:error] [pid 2939:tid 2944] [remote 127.0.0.1:58518] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:38:18.111732 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520] mod_wsgi (pid=2939): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:38:18.112013 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520] mod_wsgi (pid=2939): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:38:18.114315 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520] Traceback (most recent call last):
[Mon Nov 04 15:38:18.115278 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:38:18.115388 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]     from app import app as application
[Mon Nov 04 15:38:18.115431 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:38:18.115451 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]     import commonTasks
[Mon Nov 04 15:38:18.115476 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:38:18.115490 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520]     import gspread
[Mon Nov 04 15:38:18.115559 2024] [wsgi:error] [pid 2939:tid 2948] [remote 127.0.0.1:58520] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:34.757198 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:34.757529 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:34.759363 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580] Traceback (most recent call last):
[Mon Nov 04 15:42:34.760973 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:34.761046 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]     from app import app as application
[Mon Nov 04 15:42:34.761086 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:34.761098 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]     import commonTasks
[Mon Nov 04 15:42:34.761121 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:34.761131 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580]     import gspread
[Mon Nov 04 15:42:34.761191 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:50580] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:34.839271 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.840120 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.841880 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843074 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843162 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843200 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843210 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843232 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843242 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:34.843316 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:50590] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:36.956370 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:36.956559 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:36.957054 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602] Traceback (most recent call last):
[Mon Nov 04 15:42:36.957541 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:36.957578 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]     from app import app as application
[Mon Nov 04 15:42:36.957606 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:36.957617 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]     import commonTasks
[Mon Nov 04 15:42:36.957639 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:36.957649 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602]     import gspread
[Mon Nov 04 15:42:36.957733 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:50602] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:37.045548 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.046172 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.046938 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047550 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047626 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047660 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047673 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047695 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047704 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.047766 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:50610] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:37.657481 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:37.657680 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:37.658106 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618] Traceback (most recent call last):
[Mon Nov 04 15:42:37.658591 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:37.658637 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]     from app import app as application
[Mon Nov 04 15:42:37.658673 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:37.658687 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]     import commonTasks
[Mon Nov 04 15:42:37.658710 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:37.658720 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618]     import gspread
[Mon Nov 04 15:42:37.658782 2024] [wsgi:error] [pid 3048:tid 3092] [client 127.0.0.1:50618] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:37.917377 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:37.917663 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:37.918177 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632] Traceback (most recent call last):
[Mon Nov 04 15:42:37.918641 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:37.918685 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]     from app import app as application
[Mon Nov 04 15:42:37.918749 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:37.918761 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]     import commonTasks
[Mon Nov 04 15:42:37.918783 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:37.918793 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632]     import gspread
[Mon Nov 04 15:42:37.918838 2024] [wsgi:error] [pid 3048:tid 3094] [client 127.0.0.1:50632] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:38.046871 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.047978 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.050512 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051138 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051204 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051247 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051262 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051286 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051298 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.051349 2024] [wsgi:error] [pid 3048:tid 3096] [client 127.0.0.1:50644] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.117689 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.118067 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.118477 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658] Traceback (most recent call last):
[Mon Nov 04 15:42:38.119526 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:38.119609 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]     from app import app as application
[Mon Nov 04 15:42:38.119660 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:38.119676 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]     import commonTasks
[Mon Nov 04 15:42:38.119704 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:38.119716 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658]     import gspread
[Mon Nov 04 15:42:38.119809 2024] [wsgi:error] [pid 3048:tid 3098] [client 127.0.0.1:50658] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:38.327727 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.328012 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.328584 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668] Traceback (most recent call last):
[Mon Nov 04 15:42:38.329493 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:38.329597 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]     from app import app as application
[Mon Nov 04 15:42:38.329657 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:38.329675 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]     import commonTasks
[Mon Nov 04 15:42:38.329710 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:38.329728 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668]     import gspread
[Mon Nov 04 15:42:38.329801 2024] [wsgi:error] [pid 3048:tid 3100] [client 127.0.0.1:50668] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:38.453955 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.454155 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.454611 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455070 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455120 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455154 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455167 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455191 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455201 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.455245 2024] [wsgi:error] [pid 3048:tid 3102] [client 127.0.0.1:50674] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.516211 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.516554 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:42:38.517161 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678] Traceback (most recent call last):
[Mon Nov 04 15:42:38.517646 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:42:38.517704 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]     from app import app as application
[Mon Nov 04 15:42:38.517734 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:42:38.517746 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]     import commonTasks
[Mon Nov 04 15:42:38.517803 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:42:38.517816 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678]     import gspread
[Mon Nov 04 15:42:38.517857 2024] [wsgi:error] [pid 3048:tid 3104] [client 127.0.0.1:50678] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:42:38.679788 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.680310 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.683861 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.684846 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.684938 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.685031 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.685045 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.685072 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.685083 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.685176 2024] [wsgi:error] [pid 3049:tid 3058] [client 127.0.0.1:50624] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.692335 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.692469 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.692833 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693264 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693298 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693325 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693336 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693357 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693367 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.693407 2024] [wsgi:error] [pid 3049:tid 3059] [client 127.0.0.1:50664] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.706156 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.706314 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.706668 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707020 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707038 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707061 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707071 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707092 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707102 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:42:38.707137 2024] [wsgi:error] [pid 3049:tid 3060] [client 127.0.0.1:50688] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.037381 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.037650 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.038271 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770] Traceback (most recent call last):
[Mon Nov 04 15:44:06.039040 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:06.039132 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]     from app import app as application
[Mon Nov 04 15:44:06.039208 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:06.039242 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]     import commonTasks
[Mon Nov 04 15:44:06.039296 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:06.039322 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770]     import gspread
[Mon Nov 04 15:44:06.039410 2024] [wsgi:error] [pid 3048:tid 3106] [client 127.0.0.1:46770] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:06.113156 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.113657 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.114548 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.115783 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.115905 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.115956 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.116024 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.116057 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.116067 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.116130 2024] [wsgi:error] [pid 3048:tid 3108] [client 127.0.0.1:46776] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.697356 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.697843 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.698454 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780] Traceback (most recent call last):
[Mon Nov 04 15:44:06.699044 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:06.699102 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]     from app import app as application
[Mon Nov 04 15:44:06.699130 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:06.699141 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]     import commonTasks
[Mon Nov 04 15:44:06.699165 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:06.699175 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780]     import gspread
[Mon Nov 04 15:44:06.699231 2024] [wsgi:error] [pid 3048:tid 3085] [client 127.0.0.1:46780] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:06.774977 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.775391 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776002 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776747 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776815 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776862 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776873 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776926 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.776981 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.777059 2024] [wsgi:error] [pid 3049:tid 3062] [client 127.0.0.1:46790] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:06.954591 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.954812 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:06.955203 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800] Traceback (most recent call last):
[Mon Nov 04 15:44:06.955617 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:06.955657 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]     from app import app as application
[Mon Nov 04 15:44:06.955685 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:06.955695 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]     import commonTasks
[Mon Nov 04 15:44:06.955717 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:06.955726 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800]     import gspread
[Mon Nov 04 15:44:06.955764 2024] [wsgi:error] [pid 3048:tid 3087] [client 127.0.0.1:46800] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:07.031680 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.032021 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.032720 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033606 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033728 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033772 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033786 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033812 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033822 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.033895 2024] [wsgi:error] [pid 3049:tid 3064] [client 127.0.0.1:46806] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.192613 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.192826 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.193292 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820] Traceback (most recent call last):
[Mon Nov 04 15:44:07.194135 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:07.194187 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]     from app import app as application
[Mon Nov 04 15:44:07.194215 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:07.194226 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]     import commonTasks
[Mon Nov 04 15:44:07.194279 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:07.194289 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820]     import gspread
[Mon Nov 04 15:44:07.194331 2024] [wsgi:error] [pid 3048:tid 3089] [client 127.0.0.1:46820] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:07.274290 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.274613 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275115 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275687 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275740 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275768 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275780 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275802 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275812 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.275860 2024] [wsgi:error] [pid 3048:tid 3091] [client 127.0.0.1:46836] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.416768 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.416990 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.417404 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852] Traceback (most recent call last):
[Mon Nov 04 15:44:07.417797 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:07.417829 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]     from app import app as application
[Mon Nov 04 15:44:07.417856 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:07.417866 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]     import commonTasks
[Mon Nov 04 15:44:07.417886 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:07.417896 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852]     import gspread
[Mon Nov 04 15:44:07.417936 2024] [wsgi:error] [pid 3048:tid 3093] [client 127.0.0.1:46852] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:07.493999 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.494124 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.495516 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497325 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497540 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497623 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497642 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497668 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497680 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.497771 2024] [wsgi:error] [pid 3048:tid 3095] [client 127.0.0.1:46868] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.676290 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.676463 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.677126 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880] Traceback (most recent call last):
[Mon Nov 04 15:44:07.677605 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:07.677655 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]     from app import app as application
[Mon Nov 04 15:44:07.677688 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:07.677699 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]     import commonTasks
[Mon Nov 04 15:44:07.677721 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:07.677731 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880]     import gspread
[Mon Nov 04 15:44:07.677788 2024] [wsgi:error] [pid 3048:tid 3097] [client 127.0.0.1:46880] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:07.757116 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.757415 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.757978 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758670 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758730 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758759 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758771 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758842 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758852 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.758911 2024] [wsgi:error] [pid 3048:tid 3099] [client 127.0.0.1:46884] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.898178 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896] mod_wsgi (pid=3049): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.898495 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896] mod_wsgi (pid=3049): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'.
[Mon Nov 04 15:44:07.899079 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896] Traceback (most recent call last):
[Mon Nov 04 15:44:07.899776 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>
[Mon Nov 04 15:44:07.899865 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]     from app import app as application
[Mon Nov 04 15:44:07.899908 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]   File "/var/www/feeder/feeder/app.py", line 10, in <module>
[Mon Nov 04 15:44:07.899919 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]     import commonTasks
[Mon Nov 04 15:44:07.899941 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>
[Mon Nov 04 15:44:07.899951 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896]     import gspread
[Mon Nov 04 15:44:07.899997 2024] [wsgi:error] [pid 3049:tid 3066] [client 127.0.0.1:46896] ModuleNotFoundError: No module named 'gspread'
[Mon Nov 04 15:44:07.986050 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902] mod_wsgi (pid=3048): Failed to exec Python script file '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.986329 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902] mod_wsgi (pid=3048): Exception occurred processing WSGI script '/var/www/feeder/feeder/feeder.wsgi'., referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.986765 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902] Traceback (most recent call last):, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987183 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]   File "/var/www/feeder/feeder/feeder.wsgi", line 9, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987213 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]     from app import app as application, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987237 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]   File "/var/www/feeder/feeder/app.py", line 10, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987247 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]     import commonTasks, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987268 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]   File "/var/www/feeder/feeder/commonTasks.py", line 7, in <module>, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987278 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902]     import gspread, referer: http://127.0.0.1/
[Mon Nov 04 15:44:07.987314 2024] [wsgi:error] [pid 3048:tid 3101] [client 127.0.0.1:46902] ModuleNotFoundError: No module named 'gspread', referer: http://127.0.0.1/
